#!/bin/bash

echo "🚀 RAILWAY DEPLOYMENT QUICK START"
echo "=================================="
echo ""
echo "Prerequisites:"
echo "✓ Railway CLI installed"
echo "✓ Logged in to Railway"
echo ""
echo "Steps:"
echo ""
echo "1. Create PostgreSQL Database:"
echo "   railway add"
echo "   → Select: PostgreSQL"
echo ""
echo "2. Deploy Backend:"
echo "   cd backend"
echo "   railway up"
echo ""
echo "3. Initialize Database:"
echo "   railway run psql \$DATABASE_URL -f database/schema.sql"
echo ""
echo "4. Get your Railway URL:"
echo "   railway domain"
echo ""
echo "5. Update frontend API URL in js/api-client.js with your Railway domain"
echo ""
echo "6. Push to GitHub:"
echo "   git add ."
echo "   git commit -m \"Update Railway production URL\""
echo "   git push"
echo ""
echo "Done! Your app is live! 🎉"
